@baseUrl = https://localhost:7042

### 1. GET toutes les pizzas (pour récupérer les Guids)
GET {{baseUrl}}/pizza
Accept: application/json

### 2. POST créer une nouvelle pizza
POST {{baseUrl}}/pizza
Content-Type: application/json

{
  "name": "Calzone",
  "description": "Pliée, tomate, mozzarella, jambon",
  "price": 13.00
}

### 3. GET une pizza par Guid (copie un Id depuis le résultat du GET ci-dessus)
GET {{baseUrl}}/pizza/b408a5d4-ac61-44a4-af20-dc1e72a496d6
Accept: application/json

### 4. PUT modifier une pizza (copie un Id depuis le résultat du GET)
PUT {{baseUrl}}/pizza/b408a5d4-ac61-44a4-af20-dc1e72a496d6
Content-Type: application/json

{
  "name": "Margherita Royale",
  "description": "Tomate, mozzarella di bufala, basilic frais",
  "price": 11.50,
  "isAvailable": true
}

### 5. DELETE supprimer une pizza - Soft Delete (copie un Id)
DELETE {{baseUrl}}/pizza/40ed382d-3639-4376-90db-41c199922d85

### 6. GET pizza avec Guid inexistant (doit retourner 404)
GET {{baseUrl}}/pizza/00000000-0000-0000-0000-000000000000
Accept: application/json
