<Project Sdk="Aspire.AppHost.Sdk/13.1.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>c61f6980-4463-421e-a304-8af819654019</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.1.2" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\restaurent_pizza\restaurent_pizza.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Aspire.Hosting">
      <HintPath>..\..\..\Users\Boulot\.nuget\packages\aspire.hosting\13.1.2\lib\net8.0\Aspire.Hosting.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
